### ISSUE TITLE
Unable to join server slots >128 System.IndexOutOfRangeException 

### ISSUE THREAD

**Issue by barf** [compujuckel/AssettoServer#116]
Hello, the AssettoServer is throwing System.IndexOutOfRangeException when clients join slots >128 for me

To reproduce configure a free roam server with ~130 slots, join the slots >128, the client (AC) appears to connect but hangs after loading.
![image](https://github.com/user-attachments/assets/878197af-ec71-4542-b945-e0d6e32bb75b)

After client loads the server logs the exception as shown (steam id/ip redacted):
```
[09:26:50 DBG] Live weather: LightRain, ambient 2.34°C
[09:36:50 DBG] Live weather: LightRain, ambient 2.55°C
[09:46:51 DBG] Live weather: LightRain, ambient 2.56°C
[09:56:51 DBG] Live weather: LightRain, ambient 2.56°C
[10:05:52 INF] barf (00000000000000000 - 127.0.0.1:27633) is attempting to connect (ddm_toyota_mr2_sw20)
[10:05:52 DBG] barf supports extra CSP features: ["STEAM_TICKET", "CLIENT_MESSAGES", "SPECTATING_AWARE", "WEATHERFX_V1", "WEATHERFX_V2", "WEATHERFX_V3", "BATCH_FIX_V2", "CUSTOM_UPDATE", "CUSTOM_UPDATE_V2", "CLIENT_UDP_MESSAGES", "BATCH_MESSAGES", "EXPLICIT_ADMIN_STATE", "3117"]
[10:05:52 INF] Steam auth ticket verification succeeded for barf
[10:05:52 INF] barf (76561197966897063, 158 (ddm_toyota_mr2_sw20-itsdraik_04_black_202)) has connected
[10:06:51 DBG] Live weather: LightRain, ambient 3.15°C
Installing breakpad exception handler for appid(assettoserver)/version(1.0)/tid(56516)
Installing breakpad exception handler for appid(assettoserver)/version(1.0)/tid(56518)
[10:09:19 ERR] Error receiving TCP packet from barf
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AssettoServer.Network.Tcp.ACTcpClient.OnSpectateCar(PacketReader reader) in AssettoServer/Network/Tcp/ACTcpClient.cs:line 531
   at AssettoServer.Network.Tcp.ACTcpClient.ReceiveLoopAsync() in AssettoServer/Network/Tcp/ACTcpClient.cs:line 482
[10:09:19 DBG] Disconnecting barf (122.102.109.173:27633)
[10:09:19 INF] barf has disconnected
```

**Comment by Plaaasma** [comment]
I am having the same issue, only with some cars though.

**Comment by compujuckel** [comment]
This is a CSP bug. CSP sends a wrong ID when spectating a car with an ID > 127. The server will no longer throw an exception now, but it still needs fixing on CSP side.

Until it is fixed, spectating a player with ID > 127 will cause you to not be able to see the AI cars around them.

**Comment by barf** [comment]
Thanks compujuckel!
