### ISSUE TITLE
Client connection error - UseSteamAuth

### ISSUE THREAD

**Issue by wykydtronik** [compujuckel/AssettoServer#40]
Hello,

I setup AssettoServer Mod on Ubuntu and would like to utilize UseSteamAuth. However, clients connect to the server, I see this error.

```
[16:27:38 ERR] Error receiving TCP packet from <username>
System.NullReferenceException: Object reference not set to an instance of an object.
   at Steamworks.SteamServer.BeginAuthSession(Byte[] data, SteamId steamid)
   at AssettoServer.Server.Steam.ValidateSessionTicketAsync(Byte[] sessionTicket, String guid, ACTcpClient client) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Server/Steam.cs:line 165
   at AssettoServer.Network.Tcp.ACTcpClient.ReceiveLoopAsync() in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Network/Tcp/ACTcpClient.cs:line 294
```

I am tested with different versions of CSP 0.1.75+ (currently 0.1.78). I've even tried a suggestion to install SteamCMD.

Am I missing something?

**Comment by compujuckel** [comment]
`steamclient.so` must be placed in `/home/<user>/.steam/sdk64/`
https://wiki.facepunch.com/steamworks/Server_Library
