### ISSUE TITLE
NullReferenceException on startup

### ISSUE THREAD

**Issue by wakcs** [compujuckel/AssettoServer#9]
Just got a clean server with some cars, trying to run `pacific_coast_hwy`, and this is the first & only message I get:
```Unhandled exception occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at AssettoServer.Server.Configuration.CSPDriverOptions.Parse(String skin) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Server/Configuration/CSPDriverOptions.cs:line 9
   at AssettoServer.Server.Configuration.ACServerConfiguration.FromFiles(String preset, String serverCfgPath, String entryListPath, ACPluginLoader loader) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Server/Configuration/ACServerConfiguration.cs:line 300
   at AssettoServer.Program.Main(String[] args) in /home/runner/work/AssettoServer/AssettoServer/AssettoServer/Program.cs:line 56
   at AssettoServer.Program.<Main>(String[] args)

**Comment by compujuckel** [comment]
can you post your entry_list.ini please?

**Comment by wakcs** [comment]
[entry_list.ini.txt](https://github.com/compujuckel/AssettoServer/files/7877359/entry_list.ini.txt)

**Comment by compujuckel** [comment]
the issue is that some cars don't have a skin set. Looks like a bug, will fix it. In the mean time, specify a skin for all cars
